kind: Deployment
apiVersion: apps/v1
metadata:
    labels:
        app: employee-microservice
    name: employee-microservice
spec:
    replicas: 2
    selector:
        matchLabels:
            app: employee-microservice
    template:
        metadata:
            labels:
                app: employee-microservice
        spec:
            containers:
                -   image: dhinojosa/employeeapp:1.0.0-SNAPSHOT
                    imagePullPolicy: Always
                    env:
                        -   name: QUARKUS_DATASOURCE_USERNAME
                            valueFrom:
                                configMapKeyRef:
                                    name: database-configmap
                                    key: db.user
                        -   name: QUARKUS_DATASOURCE_JDBC_URL
                            valueFrom:
                                configMapKeyRef:
                                    name: database-configmap
                                    key: db.url
                        -   name: QUARKUS_DATASOURCE_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: fancy-unicorn-mysql
                                    key: mysql-root-password
                    name: employee-microservice
                    ports:
                        -   name: web
                            containerPort: 8080
